import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Headbar from "@/components/HeadBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "JSON Placeholder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-[100vh]`}
      >
        <div className="main-layout w-full h-full relative">
          <Headbar />
          <div className="w-full" style={{ height: "calc(100vh - 112px)" }}>
            <div className="flex flex-col w-full h-full">
              <div className="flex w-full h-1/6 items-center">
                <span className="text-2xl font-bold p-8">Comments</span>
              </div>
              <div className="flex-grow">
                <div className="flex w-full h-full justify-center items-center p-8">
                  <div className="grid gap-8 w-full h-full grid-cols-5 laptop:grid-cols-5 tablet:grid-cols-3 mobile:grid-cols-1">
                    {children}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
